export default {
  CORE_VERSION: '1.0.0',
  VERSION: '',

  // CONFIGURACION DE LA APLICACION
  REST_API: '', // DETERMINA SI ES UNA REST API O UNA APLICACION SSR
  APP_PORT: '',
  APP_TITLE: '',
  APP_NAME: '',
  SESSION_KEY: '',

  // ENTORNO DE TRABAJO
  PRODUCCION: '',

  // RECURSOS ESTATICOS Y VISTAS
  PUBLIC_ROUTE: '',
  VIEWS_ROUTE: '',
  VIEWS_ENGINE: '',
  FILE_EXTENSION: '',
  SOURCE_DIR: '',

  // CONFIGURACION DE SSL
  APP_SSL_CERT: '',
  APP_SSL_KEY: '',

  // WEBSERVICE LOCALIDADES
  WS_COMMON_URI: '',
  WS_COMMON_APIKEY: '',

  // SEGURIDAD
  SECRET: '',

  // COOKIES
  APP_COOKIE_NAME: '',
  COOKIE_EXPIRES: '',

  // CONFIGURACION DE MANEJO DE REGISTROS
  ACTIVE_DIRECTORY: '',

  // CONFIGURACION DE CAPTCHA
  CAPTCHA_MOSTRAR: '',
  CAPTCHA_SITEKEY: '',
  CAPTCHA_SECRET: '',

  // POSTGRES
  PGDB_HOST: '',
  PGDB_PORT: '',
  PGDB_USER: '',
  PGDB_PASSWORD: '',
  PGDB_NAME: '',

  // MONGO CONFIG
  MONGO_ENC_KEY: '',
  MONGO_SIGN_KEY: '',

  // MAILER CONFIG
  MAILER_HOST: '',
  MAILER_PORT: '',
  MAILER_USER: '',
  MAILER_PASS: '',
  MAILER_FROM_NAME: '',
  MAILER_FROM_ADDRESS: '',

  // CONFIGURACION DE TELEGRAM
  TELEGRAM_BOT_TOKEN: '',
  TELEGRAM_BOT_GROUP_ID: '',

  // WHATSAPP CONFIG
  URL_WHATSAPP: '',
  CHANNEL_ID_WHATSAPP: '',

  // BLOB STORAGE
  BLOB_CONNECTION: '',
  BLOB_CONTAINER: '',

  // CONFIGURACION SERVICIOS EXTERNOS
  REN_CERT: '',
  REN_URL: '',
  REN_USER: '',
  REN_PASS: '',
  REN_TTR: '',
  REN_CVEE: '',
  REN_IP: '',
  REN_TMOUT: '',

  SECONDS_IMSS_ISSSTE: '',

  END_POINT_RENAPO: '',
  END_POINT_INSABI: '',

  SEP_CEDULAS_TOKEN: '',
  SEP_CEDULA_API: ''
}